version: '3.9'
services:
  mysql-mundia:
    container_name: mysql-mundia-container
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dione1234
      - MYSQL_DATABASE=ms_product
    networks:
      dionenet:
        ipv4_address: 192.168.70.2


  php-myadmin-mundia:
    container_name: phpmyadmin-mundia
    depends_on:
      - mysql-mundia
    image: phpmyadmin/phpmyadmin
    restart: no
    ports:
      - '1010:80'
    environment:
      - PMA_HOST=mysql-mundia-container
      - MYSQL_ROOT_PASSWORD=dione1234
    networks:
      dionenet:
        ipv4_address: 192.168.70.5



  springboot-msproduct:
    container_name: springboot-msproduct-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8085:8080'
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql-mundia-container:3306/ms_product?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=dione1234
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      dionenet:
        ipv4_address: 192.168.70.6





networks:
  dionenet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
          ip_range: 192.168.70.2/25  # Plage d'adresses disponibles pour les services (192.168.70.2 à 192.168.70.126)

