version: '3.9'
services:
  mysql-employe:
    container_name: mysql-employe-container
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - '3305:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dione1234
      - MYSQL_DATABASE=ms_employe
    networks:
      employenet:
        ipv4_address: 192.168.90.2


  php-myadmin-mundia:
    container_name: phpmyadmin-employe
    depends_on:
      - mysql-employe
    image: phpmyadmin/phpmyadmin
    restart: no
    ports:
      - '1010:80'
    environment:
      - PMA_HOST=mysql-employe-container
      - MYSQL_ROOT_PASSWORD=dione1234
    networks:
      employenet:
        ipv4_address: 192.168.90.5



  springboot-msproduct:
    container_name: springboot-msemploye-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '1015:8080'
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql-employe-container:3306/ms_employe?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=dione1234
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      employenet:
        ipv4_address: 192.168.90.6





networks:
  employenet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1
          ip_range: 192.168.90.2/25  # Plage d'adresses disponibles pour les services (192.168.70.2 à 192.168.70.126)

